#!/bin/bash
## Block every IP address in ~/blocking.txt
## DROP incoming packets to avoid information leak about your hosts firewall
## (HT to Conor Mancone) REJECT outgoing packets to avoid browser wait

# flush DNS
# service nscd restart

# reset iptables
#    iptables -P INPUT ACCEPT
#    iptables -P FORWARD ACCEPT
#    iptables -P OUTPUT ACCEPT
#    iptables -t nat -F
#    iptables -t mangle -F
#    iptables -F
#    iptables -X



FLAG_IP=127.0.0.123 # ip used to determine if this script has been run

BLOCKING=($FLAG_IP \
          reddit.com www.reddit.com \
          xkcd.com www.xkcd.com \
          smbc-comics.com www.smbc-comics.com)

/sbin/iptables -L INPUT | grep $FLAG_IP > /dev/null
BLOCKED=$?
if [ $BLOCKED -gt 0 ]; then
  for i in "${BLOCKING[@]}"; do
    echo "Blocking all traffic to and from $i"
    /sbin/iptables -I INPUT -s $i -j DROP
    /sbin/iptables -I OUTPUT -d $i -j REJECT
  done
fi
