#!/bin/bash

xmodmap -pk | grep 66 | grep Escape > /dev/null
CAPS_LOCK_NOT_REMAPPED=$?
if [ "$CAPS_LOCK_NOT_REMAPPED" -gt 0 ]; then
  xmodmap -e "remove Lock = Caps_Lock" 2>/dev/null
  xmodmap -e "keycode 9 = Escape" 2>/dev/null
  xmodmap -e "keycode 66 = Escape" 2>/dev/null
  xmodmap -e "keycode 78 = Caps_Lock" 2>/dev/null
fi
