#!/bin/bash

#from http://www.stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

SOURCE="${BASH_SOURCE[0]}";
while [ -h "$SOURCE" ]; do 
# resolve until no longer a symlink
DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="$(readlink "$SOURCE")" 
[[ $SOURCE != /* ]] && 
SOURCE="$DIR/$SOURCE" 
done
TRUE_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)" 
echo "True directory: $TRUE_DIR (follows symlinks)"

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
echo Fake directory: $DIR

