#!/bin/bash
git log --format='%C(bold blue)%<(30)%aN%C(reset) %x09%C(bold green)%ae%C(reset)%C(bold yellow)%C(reset)' | awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' | sort -rn # | cut -d\  -f2- | sort -
