#!/usr/bin/python3

import sys, os, subprocess, re

#os.chdir(sys.argv[1])

#submoduleList=subprocess.check_output(["git", "submodule", "status", "--recursive"]).splitlines()
submoduleList=subprocess.check_output(["git", "-C", sys.argv[1], "submodule", "status", "--recursive"]).splitlines()
#submoduleList=subprocess.check_output(["git", "submodule", "status"]).splitlines()

def readStatus(statLine):
  #decode the line from binary
  statLine=statLine.decode('utf-8')

  regExp = '\(([^)]+)\)' # get value between parens

  #chop up the line into useful bits
  subDict={}
  subDict['modified']=statLine[0]
  subDict['short-sha']=statLine[1:9]
  subDict['sha']=statLine[1:42]
  subDict['commit']=re.search(regExp, statLine).group(0)
  commitStartPos=statLine.find(subDict['commit'])
  subDict['submodule']=statLine[43:commitStartPos - 1]
  subDict['rest']=statLine[43:]
  return subDict



for submodule in list(map(readStatus, submoduleList)):
  print('submodule: ' + submodule['submodule'])
  if (submodule['modified'] == '+'):
    print('modified: true')
  else:
    print('modified: false')
  print('commit: ' + submodule['short-sha'])
  print('')
    

