#!/bin/sh
if [ -z "$1" ] ; then
    konsole 2>/dev/null --separate --fullscreen --noclose -e $0 1
else
    TMUX=
    if [ "$(tmux ls | grep monitor | wc -l)" -eq 0 ] ; then
        #create new monitor session
        tmux new-session -d -s monitor 'exec htop'
        tmux rename-window -t monitor 'Monitor'
        tmux select-window -t monitor:0
        tmux split-window -v -t monitor:0 'while true; do if [ -e "/var/mail/$USER" ]; then tail -f "/var/mail/$USER"; else echo "no mail in /var/mail/$USER"; sleep 1; clear; fi; done'
        tmux split-window -h -t monitor:0.1 'while true; do df -h; sleep 1; clear; done'
        tmux split-window -v -t monitor:0.2 'while true; do echo -e "VMs: \n"; virsh list; sleep 1; clear; done'
    fi
    #attach to running monitor session
    tmux -2 attach-session -t monitor
fi

#see
#https://blog.serverdensity.com/80-linux-monitoring-tools-know/
#
#for more ideas
