#!/bin/sh

tmux new-session -d -s foo 'exec htop'
tmux send-keys 'bundle exec thin start' 'C-m'
tmux rename-window 'Foo'
tmux select-window -t foo:0
tmux split-window -h 'exec powertop'
tmux send-keys 'bundle exec compass watch' 'C-m'
tmux split-window -v -t 0 'exec apachetop'
tmux send-keys 'rake ts:start' 'C-m'
tmux split-window -v -t 1 'exec cmatrix'
tmux -2 attach-session -t foo


#see
#https://blog.serverdensity.com/80-linux-monitoring-tools-know/
#
#for more ideas
