#!/bin/bash

if grep -Fxq "nameserver 8.8.4.4" /etc/resolv.conf ; then
  echo -e "nameserver 8.8.4.4" | cat - /etc/resolv.conf > /tmp/resolv.conf && mv -f /tmp/resolv.conf /etc/resolv.conf
fi

if grep -Fxq "nameserver 8.8.8.8" /etc/resolv.conf ; then
  echo -e "nameserver 8.8.8.8" | cat - /etc/resolv.conf > /tmp/resolv.conf && mv -f /tmp/resolv.conf /etc/resolv.conf
fi
